# Generated by Django 3.0.4 on 2020-05-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='NULL', max_length=20)),
                ('middlename', models.CharField(default='NULL', max_length=20)),
                ('lastname', models.CharField(default='NULL', max_length=20)),
                ('waiverAcceptedDate', models.DateTimeField(blank=True, null=True)),
                ('membershipExp', models.DateTimeField(blank=True, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, default='NULL', max_length=40)),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('emergencyName', models.CharField(blank=True, default='NULL', max_length=20)),
                ('relation', models.CharField(blank=True, default='NULL', max_length=20)),
                ('emergencyPhone', models.IntegerField(blank=True, default=0)),
                ('lastVisit', models.DateTimeField(blank=True, null=True)),
                ('equity', models.IntegerField(blank=True, default=0)),
                ('waiver', models.CharField(blank=True, default='NULL', max_length=20)),
                ('permissions', models.CharField(blank=True, default='NULL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('transactionType', models.CharField(max_length=20)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('paymentType', models.IntegerField(blank=True, default=0, null=True)),
                ('paymentStatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Timelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('activity', models.CharField(choices=[('volunteering', 'volunteering'), ('member stand time', 'member stand time'), ('stand time', 'stand time'), ('shopping', 'shopping'), ('other', 'other'), ('imported login', 'imported login')], max_length=100)),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Users')),
            ],
        ),
    ]
