# Generated by Django 3.0.4 on 2020-07-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweatEquity', models.IntegerField(blank=True, default=8, null=True)),
                ('standTime', models.IntegerField(blank=True, default=4, null=True)),
                ('volunteerTime', models.IntegerField(blank=True, default=8, null=True)),
                ('volunteerAlert', models.IntegerField(blank=True, default=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewSystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('App Admin', 'App Admin'), ('Shop Admin', 'Shop Admin'), ('Kiosk', 'Kiosk')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Timelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=80)),
                ('activity', models.CharField(choices=[('volunteering', 'volunteering'), ('member stand time', 'member stand time'), ('stand time', 'stand time'), ('shopping', 'shopping'), ('other', 'other'), ('imported login', 'imported login')], max_length=100)),
                ('startTime', models.CharField(max_length=40, null=True)),
                ('endTime', models.CharField(max_length=40, null=True)),
                ('paymentType', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionPerson', models.CharField(max_length=80)),
                ('transactionType', models.CharField(choices=[('Bike Purchase', 'Bike Purchase'), ('Parts Purchase', 'Parts Purchase'), ('Volunteer Credit', 'Volunteer Credit'), ('Stand Time Purchase', 'Stand Time Purchase'), ('Imported Balance', 'Imported Balance')], max_length=40)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('paymentType', models.CharField(blank=True, choices=[('Cash/Credit', 'Cash/Credit'), ('Sweat Equity', 'Sweat Equity')], default=0, max_length=20, null=True)),
                ('paymentStatus', models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Pending', 'Pending')], default=0, max_length=20, null=True)),
                ('date', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='NULL', max_length=20)),
                ('middlename', models.CharField(default='NULL', max_length=20)),
                ('lastname', models.CharField(default='NULL', max_length=20)),
                ('waiverAcceptedDate', models.CharField(blank=True, default='NULL', max_length=40, null=True)),
                ('membershipExp', models.CharField(blank=True, default='NULL', max_length=40, null=True)),
                ('birthdate', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(blank=True, default='NULL', max_length=40)),
                ('phone', models.CharField(blank=True, default='NULL', max_length=40, null=True)),
                ('emergencyName', models.CharField(blank=True, default='NULL', max_length=20)),
                ('relation', models.CharField(blank=True, default='NULL', max_length=20)),
                ('emergencyPhone', models.CharField(blank=True, default='NULL', max_length=40)),
                ('lastVisit', models.CharField(blank=True, default='NULL', max_length=40)),
                ('equity', models.IntegerField(blank=True, default=0)),
                ('waiver', models.CharField(blank=True, default='NULL', max_length=20)),
                ('permissions', models.CharField(blank=True, default='NULL', max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('firstname', 'middlename', 'lastname'), name='unique user check'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Users'),
        ),
        migrations.AddField(
            model_name='timelogs',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Users'),
        ),
    ]
