# Generated by Django 3.0.4 on 2020-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transactionType',
            field=models.CharField(choices=[('Equity Bike Purchase', 'Equity Bike Purchase'), ('Equity Parts Purchase', 'Equity Parts Purchase')], max_length=40),
        ),
    ]
