# Generated by Django 3.0.4 on 2020-07-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelogs',
            name='paymentType',
        ),
        migrations.AddField(
            model_name='timelogs',
            name='payment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
