# Generated by Django 3.0.4 on 2020-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200513_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('App Admin', 'App Admin'), ('Shop Admin', 'Shop Admin'), ('Kiosk', 'Kiosk')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
