# Generated by Django 3.0.4 on 2020-07-26 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200726_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='users',
            field=models.ForeignKey(choices=[(1, 'Cash/Card'), (0, 'Equity')], default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Users'),
        ),
    ]
