# Generated by Django 3.0.4 on 2020-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200730_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogs',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
