# Generated by Django 3.0.4 on 2020-05-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200513_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsystemuser',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
