# Generated by Django 3.0.4 on 2020-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_timelogs_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogs',
            name='paymentStatus',
            field=models.CharField(blank=True, default='Completed', max_length=20, null=True),
        ),
    ]
