# Generated by Django 3.0.4 on 2020-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200525_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='endTime',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='emergencyPhone',
            field=models.CharField(blank=True, default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastVisit',
            field=models.CharField(blank=True, default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='membershipExp',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='waiverAcceptedDate',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
