# Generated by Django 3.0.4 on 2020-09-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200830_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='importedID',
            field=models.CharField(blank=True, default='NULL', max_length=30),
        ),
    ]
