# Generated by Django 3.0.4 on 2020-05-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200525_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweatEquity', models.IntegerField(blank=True, default=8, null=True)),
                ('standTime', models.IntegerField(blank=True, default=4, null=True)),
                ('volunteerTime', models.IntegerField(blank=True, default=8, null=True)),
            ],
        ),
    ]
