# Generated by Django 3.0.4 on 2020-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_users_importedid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogs',
            name='importedTimelogId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timelogs',
            name='importedTransactionId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timelogs',
            name='importedUserId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
