# Generated by Django 3.0.4 on 2020-06-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_equityrates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='person',
            new_name='transactionPerson',
        ),
    ]
