# Generated by Django 3.0.4 on 2020-06-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200605_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityrates',
            name='volunteerAlert',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
