# Generated by Django 3.0.4 on 2020-09-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200906_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='importedTransactionId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='importedUserId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
