# Generated by Django 3.0.4 on 2020-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_equityrates_volunteeralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='NULL', max_length=40),
        ),
    ]
