# Generated by Django 3.0.4 on 2020-07-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200626_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='membershipExp',
            field=models.CharField(blank=True, default='NULL', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='waiverAcceptedDate',
            field=models.CharField(blank=True, default='NULL', max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('firstname', 'middlename', 'lastname', 'birthdate'), name='unique user check'),
        ),
    ]
