# Generated by Django 3.0.4 on 2022-02-12 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220203_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 11, 9, 54, 132992)),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 11, 9, 54, 132962)),
        ),
    ]
