# Generated by Django 3.0.4 on 2022-02-16 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220212_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelogs',
            name='hours',
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 6, 37, 4, 147418)),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 6, 37, 4, 147385)),
        ),
    ]
