# Generated by Django 3.0.4 on 2022-02-16 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20220216_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 6, 46, 10, 48173)),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 6, 46, 10, 48143)),
        ),
    ]
