# Generated by Django 3.0.4 on 2022-02-18 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20220216_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 13, 25, 49, 415148)),
        ),
    ]
