# Generated by Django 3.0.4 on 2022-02-18 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20220218_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 13, 27, 56, 522928)),
        ),
    ]
