# Generated by Django 3.0.4 on 2022-03-10 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220218_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 17, 26, 36, 575949, tzinfo=utc)),
        ),
    ]
